# RFM Customer Classification

## Charger les Donées

In [1]:
# Importer les librairies nécessaires

import pandas as pd

In [2]:
# Charger le csv

path = r'C:\Users\shree\Documents\Professional\Job Search 25-26\Interview Prep\PSG\Case Study - PSG\Case Study - PSG\Work\Data\Analysis'
file = r'rfm.csv'

rfm = pd.read_csv(r'{}\{}'.format(path, file), sep = '\t', encoding = 'utf-16')

rfm.describe()

          Frequency
count  12302.000000
mean       1.142660
std        0.904991
min        1.000000
25%        1.000000
50%        1.000000
75%        1.000000
max       34.000000

In [3]:
rfm.dtypes

Unnamed: 0        object
Recency           object
Frequency          int64
Monetary Value    object
dtype: object

In [4]:
rfm.head()

                             Unnamed: 0 Recency  Frequency Monetary Value
0  1010397c-350c-447f-a748-89c1be83f06c     306         34         11,692
1  037e72ab-36b4-4c25-817b-3d36dbe6e02f     356         34         10,903
2  709827c2-e5ce-4f02-89e7-340d4abac579     320         27         21,305
3  e5e6e66d-1e1c-4153-bd60-5889ba2eba60     448         24         68,964
4  ba21bad6-fc6c-4ff3-9aba-6619b654777c     311         24         35,887

In [5]:
# Supprimer les ',' en Monetary Value et Recency
# Changer les datatypes au int64

columns = ['Recency', 'Monetary Value']

for col in columns:
    rfm[col] = rfm[col].str.replace(',', '')
    rfm[col] = rfm[col].astype('Int64')

rfm.describe()

          Recency     Frequency  Monetary Value
count     12302.0  12302.000000         12067.0
mean   677.749634      1.142660      1190.81437
std    197.698378      0.904991    38882.052065
min         306.0      1.000000             0.0
25%         494.0      1.000000           138.0
50%         737.0      1.000000           230.0
75%         843.0      1.000000           400.0
max        1119.0     34.000000       3873337.0

In [6]:
# Scorer la récence, fréquence, et valeur monétaire des clients en quartiles

labels = [1, 2, 3, 4]

rfm['recency_score'] = pd.qcut(rfm['Recency'], q = 4, labels = labels[::-1])
rfm['frequency_score'] = pd.cut(rfm['Frequency'], bins = [0, 1, 2, 5, 99], labels = [1, 2, 3, 4])
rfm['monetary_score'] = pd.qcut(rfm['Monetary Value'], q = 4, labels = labels)

rfm.tail()

,Unnamed: 0,Recency,Frequency,Monetary Value,recency_score,frequency_score,monetary_score
12297,002374b9-8a62-4af8-a92f-9734208a9f87,848,1,199,1,1,2
12298,00198fb2-fd82-4f4a-a8a0-30fdfd642e52,714,1,250,3,1,3
12299,0011c7b3-ec27-4ce4-ad9c-74639dcc60ab,782,1,234,2,1,3
12300,000e038b-682b-4112-8c5c-3072669090fe,829,1,190,2,1,2
12301,00040c20-d17d-4a01-9def-c35d7c06aec5,531,1,296,3,1,3

In [7]:
# Changer nom de la 1e colonne

rfm.rename({'Unnamed: 0':'fan_id'}, axis = 1, inplace = True)
rfm.head()

,fan_id,Recency,Frequency,Monetary Value,recency_score,frequency_score,monetary_score
0,1010397c-350c-447f-a748-89c1be83f06c,306,34,11692,4,4,4
1,037e72ab-36b4-4c25-817b-3d36dbe6e02f,356,34,10903,4,4,4
2,709827c2-e5ce-4f02-89e7-340d4abac579,320,27,21305,4,4,4
3,e5e6e66d-1e1c-4153-bd60-5889ba2eba60,448,24,68964,4,4,4
4,ba21bad6-fc6c-4ff3-9aba-6619b654777c,311,24,35887,4,4,4

In [8]:
recency_score = rfm['recency_score']
frequency_score = rfm['frequency_score']
monetary_score = rfm['monetary_score']

rfm_score = []

for i in range(len(recency_score)):
    score = r'{}{}{}'.format(recency_score[i], frequency_score[i], monetary_score[i])
    rfm_score.append(score)

rfm['rfm_score'] = rfm_score

rfm.head()

,fan_id,Recency,Frequency,Monetary Value,recency_score,frequency_score,monetary_score,rfm_score
0,1010397c-350c-447f-a748-89c1be83f06c,306,34,11692,4,4,4,444
1,037e72ab-36b4-4c25-817b-3d36dbe6e02f,356,34,10903,4,4,4,444
2,709827c2-e5ce-4f02-89e7-340d4abac579,320,27,21305,4,4,4,444
3,e5e6e66d-1e1c-4153-bd60-5889ba2eba60,448,24,68964,4,4,4,444
4,ba21bad6-fc6c-4ff3-9aba-6619b654777c,311,24,35887,4,4,4,444

## Exporter les Données

In [9]:
# Selectionner uniquement les colonnes nécessaires : fan_id et rfm_score

rfm_final = rfm[['fan_id', 'rfm_score']]

In [10]:
rfm_final.to_csv(r'C:\Users\shree\Documents\Professional\Job Search 25-26\Interview Prep\PSG\Case Study - PSG\Case Study - PSG\Work\Data\Analysis\rfm_scored.csv')

In [16]:
rfm[rfm['recency_score'] == 3]['Recency'].max() - 306

np.int64(431)

In [31]:
rfm[rfm['monetary_score'] == 4]['Monetary Value'].describe()

count          2955.0
mean      4263.167851
std      78502.669891
min             401.0
25%             480.0
50%             600.0
75%             900.0
max         3873337.0
Name: Monetary Value, dtype: Float64

In [28]:
rfm[rfm['recency_score'] <= 2]['Recency'].describe()

count        9237.0
mean      600.87182
std      166.699816
min           306.0
25%           448.0
50%           563.0
75%           768.0
max           843.0
Name: Recency, dtype: Float64

In [30]:
843 - 306

537